name: Continuous Integration

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - 'development'
      - 'master'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Force install problematic package
        run: npm install eslint-plugin-cypress

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test:ci

      - name: Run E2E tests
        run: npm run e2e
